### ISSUE TITLE
Reproducing the notebooks

### ISSUE THREAD

**Issue by tzubad** [yangbang18/CARE#2]
While trying to run 'VATEX_qualitative_examples', I've encountered this error:

FileNotFoundError: [Errno 2] No such file or directory: 'c:/Users/User/Desktop/Video2Desc/CARE/exps/VATEX/Transformer/Base/median_ViT_ami/best.ckpt'

This makes sense since folder 'exps' doesn't exist in this repository.
How can I reproduce that folder?

**Comment by yangbang18** [comment]
Hi, to run `notebooks/VATEX_qualitative_examples.ipynb`, you should first conduct experiments (i.e., train models) on the VATEX dataset. 

For example, to obtain `exps/VATEX/Transformer/Base/median_ViT_ami/best.ckpt`, you can run the following command:
```
base_cmd="python train.py \
--dataset VATEX \
--method Transformer \
--VATEX_I3D_preds_json ./data/VATEX_I3D_preds.json"

cmd="$base_cmd --task Base --arch median --feats ViT --modality ami"
bash scripts/run.sh "$cmd" $num_runs $gpu
```
**Note:** Please ensure that you have downloaded VATEX pre-processed data following [README_DATA.md](https://github.com/yangbang18/CARE/blob/master/README_DATA.md).

More details can refer to [scripts/exp_main_VATEX.sh](https://github.com/yangbang18/CARE/blob/246f2ff9ce3bcf5a769d9c2d9788a6936d42df2e/scripts/exp_main_VATEX.sh).

**Comment by tzubad** [comment]
Thank you for the explanation, I'll try that!
