### ISSUE TITLE
VATEX dataset download

### ISSUE THREAD

**Issue by draym28** [yangbang18/CARE#3]
I tried to download VATEX dataset from your links, both PKU disc and OneDrive, but I cannot unzip the `VATEX.zip` file because it said that the file is broken. 

Could you provide some alternative download links, such as BaiduYunPan?

**Comment by yangbang18** [comment]
I will check it out and fix it, stay tuned :)

**Comment by draym28** [comment]
> I will check it out and fix it, stay tuned :)

Thanks!

**Comment by yangbang18** [comment]
I have checked the OneDrive's download link for `VATEX.zip` and the downloaded file can be unzipped.

For convenience, you can use [BaiduYun](https://pan.baidu.com/s/1Vr1ppSCmKBNfMNfSf0w2rA) (extract code: `t3ge`) to download `VATEX`.

**Comment by draym28** [comment]
> I have checked the OneDrive's download link for `VATEX.zip` and the downloaded file can be unzipped.
> 
> 
> 
> For convenience, you can use [BaiduYun](https://pan.baidu.com/s/1Vr1ppSCmKBNfMNfSf0w2rA) (extract code: `t3ge`) to download `VATEX`. 

Thanks! I have unzipped it successfully.
